# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyfire < Formula
  desc "Terminal UI for browsing Firebase Firestore"
  homepage "https://github.com/marjoballabani/lazyfire"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/marjoballabani/lazyfire/releases/download/v0.1.3/lazyfire_0.1.3_darwin_amd64.tar.gz"
      sha256 "598c4b88fa09c73e649bd100d6147270a6b8c054b4348a3d66a5f65a9f07b569"

      def install
        bin.install "lazyfire"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/marjoballabani/lazyfire/releases/download/v0.1.3/lazyfire_0.1.3_darwin_arm64.tar.gz"
      sha256 "f5e9094615f49ef087338ea2066d6db424b6b86652546b81c6db3310ee1c6171"

      def install
        bin.install "lazyfire"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/marjoballabani/lazyfire/releases/download/v0.1.3/lazyfire_0.1.3_linux_amd64.tar.gz"
      sha256 "7ba7752f354aace5c3066a6bb613f3121b1bf8786b822f72d15c8a5a96dba99e"
      def install
        bin.install "lazyfire"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/marjoballabani/lazyfire/releases/download/v0.1.3/lazyfire_0.1.3_linux_arm64.tar.gz"
      sha256 "04a5c1061c5f57a970e11e08edd4e008f871a83f6ceb446536dad56f5556f634"
      def install
        bin.install "lazyfire"
      end
    end
  end

  test do
    system "#{bin}/lazyfire", "--version"
  end
end
