# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyfire < Formula
  desc "Terminal UI for browsing Firebase Firestore"
  homepage "https://github.com/marjoballabani/lazyfire"
  version "0.1.41"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/marjoballabani/lazyfire/releases/download/v0.1.41/lazyfire_0.1.41_darwin_amd64.tar.gz"
      sha256 "50402e8d968c0d172fa5106f6c8ee1d4c169c3fe9ad343e54c75d1598239568e"

      define_method(:install) do
        bin.install "lazyfire"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/marjoballabani/lazyfire/releases/download/v0.1.41/lazyfire_0.1.41_darwin_arm64.tar.gz"
      sha256 "9d2febf169aa26a0b3de6930e0cea28dc4c0b27ceee3aa70053fb481f987051e"

      define_method(:install) do
        bin.install "lazyfire"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/marjoballabani/lazyfire/releases/download/v0.1.41/lazyfire_0.1.41_linux_amd64.tar.gz"
      sha256 "1e083f07e48215538ef18a3e3a288e1a83f8622e70a22ea65de8df4460ef281d"
      define_method(:install) do
        bin.install "lazyfire"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/marjoballabani/lazyfire/releases/download/v0.1.41/lazyfire_0.1.41_linux_arm64.tar.gz"
      sha256 "702007321e23729faa70706fee128ac0ad305b079b08159ecfe889edb5714f79"
      define_method(:install) do
        bin.install "lazyfire"
      end
    end
  end

  test do
    system "#{bin}/lazyfire", "--version"
  end
end
