# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyfire < Formula
  desc "Terminal UI for browsing Firebase Firestore"
  homepage "https://github.com/marjoballabani/lazyfire"
  version "0.1.33"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/marjoballabani/lazyfire/releases/download/v0.1.33/lazyfire_0.1.33_darwin_amd64.tar.gz"
      sha256 "c15ef9c935f1c31976fb8a8dec33edde57cb85766192f2ed8c7c1d2ca93edd04"

      def install
        bin.install "lazyfire"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/marjoballabani/lazyfire/releases/download/v0.1.33/lazyfire_0.1.33_darwin_arm64.tar.gz"
      sha256 "6d47fbb1916a150da9b54c7cd7d99263e9d7e64217a220890bda477c32d66d50"

      def install
        bin.install "lazyfire"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/marjoballabani/lazyfire/releases/download/v0.1.33/lazyfire_0.1.33_linux_amd64.tar.gz"
      sha256 "42257d838e73136fa9423af924e38777a02162f0078d31a06b566600b803271e"
      def install
        bin.install "lazyfire"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/marjoballabani/lazyfire/releases/download/v0.1.33/lazyfire_0.1.33_linux_arm64.tar.gz"
      sha256 "dd47645f9c9683e514b31a485ac6d91366a396969838c8f5aea83fbaffea67f4"
      def install
        bin.install "lazyfire"
      end
    end
  end

  test do
    system "#{bin}/lazyfire", "--version"
  end
end
